---

#############################
# Gather environment stuff
#############################

- stat: path=/usr/sbin/php-fpm7.0
  register: php7_debian

- name: Fact - php5 pool [RedHat family]
  set_fact:
     php_pool_conf: /etc/php-fpm.d/www.conf
  when: ansible_os_family == 'RedHat'

- name: Fact - php5 pool [Debian family]
  set_fact:
     php_pool_conf: /etc/php5/fpm/pool.d/www.conf
  when: ansible_os_family == 'Debian'

- name: Fact - php7 pool [Debian family]
  set_fact:
     php_pool_conf: /etc/php/7.0/fpm/pool.d/www.conf
  when: ansible_os_family == 'Debian' and php7_debian.stat.exists is defined and php7_debian.stat.exists

#############################
# Run tasks
#############################

- include: entrypoint/mysql.yml
- include: entrypoint/php.yml php_pool_conf="{{ php_pool_conf }}"
