#######################################
# Main php container
#######################################
main:
  ## Ubuntu
  build: docker/main/ubuntu
  #dockerfile: Ubuntu-12.04 # Ubuntu 12.04 - PHP 5.3, LTS (precise)
  dockerfile: Ubuntu-14.04 # Ubuntu 14.04 - PHP 5.5, LTS (trusty)
  #dockerfile: Ubuntu-15.04 # Ubuntu 15.04 - PHP 5.6 (vivid)
  #dockerfile: Ubuntu-15.10 # Ubuntu 15.10 - PHP 5.6 (wily)
  #dockerfile: Ubuntu-HHVM  # Ubuntu 14.04 - HHVM (trusty)
  #dockerfile: Centos-7     # CentOS 7     - PHP 5.4
  links:
    - mysql
    #- postgres
    #- mail
    #- solr
    #- elasticsearch
    #- redis
    #- memcached
    #- ftp
  volumes:
    - ./:/docker/
    - /tmp/debug/:/tmp/debug/
  volumes_from:
    - storage
  # cap and privileged needed for slowlog
  cap_add:
    - SYS_PTRACE
  privileged: true
  env_file:
    - docker-env.yml

#######################################
# Webserver
#######################################
web:
  build: docker/web/httpd/   # Apache HTTPD webserver
  #build: docker/web/nginx/  # Nginx
  ports:
    - 8000:80
    - 8443:443
  links:
    - main
  volumes_from:
    - main
    - storage
  env_file:
    - docker-env.yml

#######################################
# MySQL server
#######################################
mysql:
  build: docker/mysql/  # MySQL, MariaDB or PerconaDB
  ports:
    - 13306:3306
  volumes_from:
    - storage
  volumes:
    - /tmp/debug/:/tmp/debug/
  env_file:
    - docker-env.yml

#######################################
# PostgreSQL server
#######################################
#postgres:
#  build: docker/postgres/
#  ports:
#    - 15432:5432
#  volumes_from:
#    - storage
#  env_file:
#    - docker-env.yml

#######################################
# Solr server
#######################################
#solr:
#  build: docker/solr/
#  ports:
#    - 18983:8983
#  volumes_from:
#    - storage
#  environment:
#    - SOLR_STORAGE=/data/solr/server-master/
#  env_file:
#    - docker-env.yml

#######################################
# Elasticsearch
#######################################
#elasticsearch:
#  build: docker/elasticsearch/
#  ports:
#    - 19200:9200
#    - 19300:9300
#  volumes_from:
#    - storage
#  env_file:
#    - docker-env.yml

#######################################
# Redis
#######################################
#redis:
#  build: docker/redis/
#  volumes_from:
#    - storage
#  env_file:
#    - docker-env.yml

#######################################
# Memcached
#######################################
#memcached:
#  build: docker/memcached/
#  volumes_from:
#    - storage
#  env_file:
#    - docker-env.yml

#######################################
# Mailcatcher
#######################################
#mail:
#  build: docker/mail/
#  ports:
#    - 1080:1080
#  env_file:
#    - docker-env.yml

#######################################
# FTP (vsftpd)
#######################################
#ftp:
#  build: docker/vsftpd/
#  volumes_from:
#    - storage
#  volumes:
#    - ./:/docker/
#    - /tmp/debug/:/tmp/debug/
#  env_file:
#    - docker-env.yml

#######################################
# Storage
#######################################
storage:
  build: docker/storage/
  volumes:
    - /data
