---

- name: Install cron
  apt:
    name:  '{{ item }}'
    state: present
  when: ansible_distribution == 'Ubuntu'
  with_items:
    - cron
    - anacron

- name: Install cron
  yum:
    name:  '{{ item }}'
    state: present
  when: ansible_distribution == 'CentOS'
  with_items:
    - cronie

- name: Create link for crontab
  file:
    src:  '/opt/docker/conf/crontab'
    dest: '/etc/cron.d/docker-boilerplate'
    state: link
    force: yes
