---

DOCKER_ENVIRONMENT:
  # General
  CLI_SCRIPT:          "{{ lookup('env','CLI_SCRIPT') }}"
  MAIL_GATEWAY:        "{{ lookup('env','MAIL_GATEWAY') }}"

  # MySQL
  MYSQL_ROOT_PASSWORD: "{{ lookup('env','MYSQL_ROOT_PASSWORD') }}"
  MYSQL_USER:          "{{ lookup('env','MYSQL_USER') }}"
  MYSQL_PASSWORD:      "{{ lookup('env','MYSQL_PASSWORD') }}"
  MYSQL_DATABASE:      "{{ lookup('env','MYSQL_DATABASE') }}"

  # Postgres
  POSTGRES_USER:       "{{ lookup('env','POSTGRES_USER') }}"
  POSTGRES_PASSWORD:   "{{ lookup('env','POSTGRES_PASSWORD') }}"

  # FTP
  FTP_USER:            "{{ lookup('env','FTP_USER') }}"
  FTP_PASSWORD:        "{{ lookup('env','FTP_PASSWORD') }}"
  FTP_PATH:            "{{ lookup('env','FTP_PATH') }}"

PHP:
  pm:
    maxChildren: 30
    startServers: 10
    minSpareServers: 5
    maxSpareServers: 10
