---

WEB:
  VHOST:
    - { serverName: "docker.vm", serverAlias: "*.vm" }

ENVIRONMENT:
  TYPO3_CONTEXT: 'Development/Docker'

PHP:
  pm:
    maxChildren: 15
    startServers: 2
    minSpareServers: 1
    maxSpareServers: 3
