- hosts: all
  vars_files:
    - /opt/docker/provision/variables.yml
  roles:
    - init
    - { role: update,  when: PROVISION.SYS.UPDATE == "1" }
    - packages
    - locales
    - users
    - supervisord
    - dnsmasqd
    - cron
    - ssmtp
    - { role: php,  when: PROVISION.PHP.DISTRIBUTION == "php" }
    - { role: hhvm, when: PROVISION.PHP.DISTRIBUTION == "hhvm" }
    - mysql
    - composer
    - finalize
