---

- name: Set development environment php.ini
  file:
    src:  '/opt/docker/etc/php/development.ini'
    dest: '/opt/docker/etc/php/php.ini'
    state: link
    force: yes
  when: PROVISION_CONTEXT == "development" or PROVISION_CONTEXT == ""

- name: Enable production environment php.ini
  file:
    src:  '/opt/docker/etc/php/production.ini'
    dest: '/opt/docker/etc/php/php.ini'
    state: link
    force: yes
  when: PROVISION_CONTEXT == "production"
