---

- name: Install hhvm gpg key
  apt_key:
    url: http://dl.hhvm.com/conf/hhvm.gpg.key
    state: present

- name: Add hhvm deb repository
  apt_repository:
    repo:  'deb http://dl.hhvm.com/ubuntu trusty main'
    state: present

- name: Install hhvm packages
  apt:
    pkg: '{{ item }}'
    state: latest
    update_cache: yes
    force: yes
  with_items:
      - hhvm-fastcgi

- name: check hhvm path
  shell: which hhvm
  register: current_hhvm
  ignore_errors: True

- name: Symlink hhvm as php
  file:
    src:   '{{ current_hhvm.stdout }}'
    dest:  /usr/bin/php
    state: link
    force: yes
