---

- name: Install openssh server
  apt:
    name:  '{{ item }}'
    state: present
  when: ansible_distribution == 'Ubuntu'
  with_items:
    - openssh-server

- name: Install openssh server
  yum:
    name:  '{{ item }}'
    state: present
  when: ansible_distribution == 'CentOS'
  with_items:
    - openssh-server

- name: Create /var/run/sshd
  file:
    path:  /var/run/sshd
    state: directory
    mode:  0700

